spring.application.name=Teacher

###Db url
spring.datasource.url=jdbc:postgresql://localhost:5432/teacherdb
###Create or update table automatically
spring.jpa.hibernate.ddl-auto=update
###Show SQL commands
spring.jpa.show-sql=true
###Db Authentication/Connect to postgreSQL
spring.datasource.username=postgres
spring.datasource.password=suvam123
###Browser Authentication/Custom User Login
spring.security.user.name=suvam
spring.security.user.password=suvam123