spring.application.name=Teacher

###Db url
spring.datasource.url=jdbc:postgresql://localhost:5432/teacherdb
###Create or update table automatically
spring.jpa.hibernate.ddl-auto=update
###Show SQL commands
spring.jpa.show-sql=true
###Own Custom Login
spring.datasource.username=suvam
spring.datasource.password=suvam123