spring.application.name=spring-token-practice

###Connect postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/suvam1
spring.datasource.username=postgres
spring.datasource.password=0000

###To see sql-queries
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

