spring.application.name=crud-practice

###To start h2 database
spring.h2.console.enabled=true

###To set JDBC URL
spring.datasource.url=jdbc:h2:mem:suvam

##Set Login
spring.datasource.username=suvamgrng
spring.datasource.password=suvam123